### ISSUE TITLE
how to filter search limited to app 

### ISSUE THREAD

**Issue by yashwanth2804** [Hoxly/asksteem-docs#1]
`https://api.asksteem.com/search?q=tags:dmania+AND+meta.app:dmania&include=meta`
I used above url to get posts from dmania filtering only dmania app, but problem is when i switch to next page ,causing logic issue . nothing is changing

`https://api.asksteem.com/search?q=tags:dmania+AND+meta.app:dmania&include=meta&pg:2`

**Comment by KylePiira** [comment]
Hi there, you need to use `&pg=2` instead of `&pg:2` at the end instead. A quick tip is that if you ever get stuck you can try replacing `api` with `www` in the URL to see how the main AskSteem website handles things.

Here is the correct full URL: `https://api.asksteem.com/search?q=tags:dmania%20AND%20meta.app:dmania&pg=2`

For easy viewing you can also see the HTML results here: `https://www.asksteem.com/search?q=tags:dmania%20AND%20meta.app:dmania&pg=2`
